"""create corporation ctc model

Revision ID: a0c296de50c0
Revises: 916b87941508
Create Date: 2024-10-21 06:57:36.597864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c296de50c0'
down_revision: Union[str, None] = '916b87941508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporation_ctcs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ctc_number', sa.String(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('place_of_issue', sa.String(), nullable=True),
    sa.Column('date_issued', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('tin', sa.Integer(), nullable=True),
    sa.Column('business_address', sa.String(), nullable=True),
    sa.Column('date_of_registration', sa.Date(), nullable=True),
    sa.Column('organization_type', sa.Enum('CORPORATION', 'ASSOCIATION', 'PARTNERSHIP', name='organizationtypeenum'), nullable=True),
    sa.Column('place_of_incorporation', sa.String(), nullable=True),
    sa.Column('nature_of_business', sa.String(), nullable=True),
    sa.Column('basic_community_tax', sa.Float(), nullable=True),
    sa.Column('taxable_assessed_value', sa.Float(), nullable=True),
    sa.Column('taxable_gross', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('year >= 1900 AND year <= 2999', name='ck_year'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ctc_number', name='uk_corp_ctc_number')
    )
    op.create_index(op.f('ix_corporation_ctcs_ctc_number'), 'corporation_ctcs', ['ctc_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporation_ctcs_ctc_number'), table_name='corporation_ctcs')
    op.drop_table('corporation_ctcs')
    # ### end Alembic commands ###
