name: Validate Docker Build on PRs

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  validate:
    name: Validate Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t test-image .
